## Target Guided Ordinal Encoding 
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [9]:
import pandas as pd

# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [10]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [11]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [12]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [13]:
df['city_encoded']=df['city'].map(mean_price)

In [14]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

In [15]:
import seaborn as sns
df = sns.load_dataset('tips')

In [16]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [17]:
mean_time=df.groupby('time')['total_bill'].mean().to_dict()

/var/folders/kz/drzzdzz94lx_gv8ps7nxdxg40000gn/T/ipykernel_1271/1858858511.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_time=df.groupby('time')['total_bill'].mean().to_dict()

In [20]:
df['time_encoded']=df['time'].map(mean_time)

In [26]:
df['time_encoded'].value_counts()

time_encoded
20.797159    176
17.168676     68
Name: count, dtype: int64

In [25]:
df[['time_encoded','time']]

    time_encoded    time
0      20.797159  Dinner
1      20.797159  Dinner
2      20.797159  Dinner
3      20.797159  Dinner
4      20.797159  Dinner
..           ...     ...
239    20.797159  Dinner
240    20.797159  Dinner
241    20.797159  Dinner
242    20.797159  Dinner
243    20.797159  Dinner

[244 rows x 2 columns]